/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthorRouteRouteImport } from './routes/author/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTranslationRequestsRouteImport } from './routes/admin/translation-requests'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as AuthorAuthorIdRouteImport } from './routes/author/$authorId'
import { Route as AuthorAnalyticsRouteImport } from './routes/author.analytics'
import { Route as AuthorPublishRouteImport } from './routes/author.publish'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as ResearchPaperIdRouteImport } from './routes/research/$paperId'
import { Route as ResearchMineRouteImport } from './routes/research/mine'
import { Route as ResearchSubmitRouteImport } from './routes/research/submit'
import { Route as AdminBooksIndexRouteImport } from './routes/admin/books/index'
import { Route as AdminBooksBookIdRouteImport } from './routes/admin/books/$bookId'
import { Route as AdminBooksNewRouteImport } from './routes/admin/books/new'
import { Route as AdminResearchIndexRouteImport } from './routes/admin/research/index'
import { Route as AdminResearchPaperIdRouteImport } from './routes/admin/research/$paperId'
import { Route as AdminSupportIndexRouteImport } from './routes/admin/support/index'
import { Route as AdminSupportTicketIdRouteImport } from './routes/admin/support/$ticketId'
import { Route as AuthorBookBookIdRouteImport } from './routes/author.book.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRouteRoute = AuthorRouteRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTranslationRequestsRoute =
  AdminTranslationRequestsRouteImport.update({
    id: '/translation-requests',
    path: '/translation-requests',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthorAuthorIdRoute = AuthorAuthorIdRouteImport.update({
  id: '/$authorId',
  path: '/$authorId',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthorAnalyticsRoute = AuthorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthorPublishRoute = AuthorPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPaperIdRoute = ResearchPaperIdRouteImport.update({
  id: '/research/$paperId',
  path: '/research/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchMineRoute = ResearchMineRouteImport.update({
  id: '/research/mine',
  path: '/research/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSubmitRoute = ResearchSubmitRouteImport.update({
  id: '/research/submit',
  path: '/research/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBooksBookIdRoute = AdminBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBooksNewRoute = AdminBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResearchIndexRoute = AdminResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResearchPaperIdRoute = AdminResearchPaperIdRouteImport.update({
  id: '/research/$paperId',
  path: '/research/$paperId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportTicketIdRoute = AdminSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthorBookBookIdRoute = AuthorBookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => AuthorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/author': typeof AuthorRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translation-requests': typeof AdminTranslationRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/author/analytics': typeof AuthorAnalyticsRoute
  '/author/publish': typeof AuthorPublishRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/research/$paperId': typeof ResearchPaperIdRoute
  '/research/mine': typeof ResearchMineRoute
  '/research/submit': typeof ResearchSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/author/': typeof AuthorIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/admin/books/$bookId': typeof AdminBooksBookIdRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/research/$paperId': typeof AdminResearchPaperIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/author/book/$bookId': typeof AuthorBookBookIdRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/research/': typeof AdminResearchIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translation-requests': typeof AdminTranslationRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/author/analytics': typeof AuthorAnalyticsRoute
  '/author/publish': typeof AuthorPublishRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/research/$paperId': typeof ResearchPaperIdRoute
  '/research/mine': typeof ResearchMineRoute
  '/research/submit': typeof ResearchSubmitRoute
  '/admin': typeof AdminIndexRoute
  '/author': typeof AuthorIndexRoute
  '/research': typeof ResearchIndexRoute
  '/admin/books/$bookId': typeof AdminBooksBookIdRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/research/$paperId': typeof AdminResearchPaperIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/author/book/$bookId': typeof AuthorBookBookIdRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/research': typeof AdminResearchIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/author': typeof AuthorRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translation-requests': typeof AdminTranslationRequestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/author/analytics': typeof AuthorAnalyticsRoute
  '/author/publish': typeof AuthorPublishRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/research/$paperId': typeof ResearchPaperIdRoute
  '/research/mine': typeof ResearchMineRoute
  '/research/submit': typeof ResearchSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/author/': typeof AuthorIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/admin/books/$bookId': typeof AdminBooksBookIdRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/research/$paperId': typeof AdminResearchPaperIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/author/book/$bookId': typeof AuthorBookBookIdRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/research/': typeof AdminResearchIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/author'
    | '/auth'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/profile'
    | '/subscribe'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/translation-requests'
    | '/admin/users'
    | '/auth/reset-password'
    | '/author/$authorId'
    | '/author/analytics'
    | '/author/publish'
    | '/book/$bookId'
    | '/read/$bookId'
    | '/research/$paperId'
    | '/research/mine'
    | '/research/submit'
    | '/admin/'
    | '/author/'
    | '/research/'
    | '/admin/books/$bookId'
    | '/admin/books/new'
    | '/admin/research/$paperId'
    | '/admin/support/$ticketId'
    | '/author/book/$bookId'
    | '/admin/books/'
    | '/admin/research/'
    | '/admin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/profile'
    | '/subscribe'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/translation-requests'
    | '/admin/users'
    | '/auth/reset-password'
    | '/author/$authorId'
    | '/author/analytics'
    | '/author/publish'
    | '/book/$bookId'
    | '/read/$bookId'
    | '/research/$paperId'
    | '/research/mine'
    | '/research/submit'
    | '/admin'
    | '/author'
    | '/research'
    | '/admin/books/$bookId'
    | '/admin/books/new'
    | '/admin/research/$paperId'
    | '/admin/support/$ticketId'
    | '/author/book/$bookId'
    | '/admin/books'
    | '/admin/research'
    | '/admin/support'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/author'
    | '/auth'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/profile'
    | '/subscribe'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/translation-requests'
    | '/admin/users'
    | '/auth/reset-password'
    | '/author/$authorId'
    | '/author/analytics'
    | '/author/publish'
    | '/book/$bookId'
    | '/read/$bookId'
    | '/research/$paperId'
    | '/research/mine'
    | '/research/submit'
    | '/admin/'
    | '/author/'
    | '/research/'
    | '/admin/books/$bookId'
    | '/admin/books/new'
    | '/admin/research/$paperId'
    | '/admin/support/$ticketId'
    | '/author/book/$bookId'
    | '/admin/books/'
    | '/admin/research/'
    | '/admin/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthorRouteRoute: typeof AuthorRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LegalRoute: typeof LegalRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SubscribeRoute: typeof SubscribeRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
  ResearchPaperIdRoute: typeof ResearchPaperIdRoute
  ResearchMineRoute: typeof ResearchMineRoute
  ResearchSubmitRoute: typeof ResearchSubmitRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/translation-requests': {
      id: '/admin/translation-requests'
      path: '/translation-requests'
      fullPath: '/admin/translation-requests'
      preLoaderRoute: typeof AdminTranslationRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/author/': {
      id: '/author/'
      path: '/'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/author/$authorId': {
      id: '/author/$authorId'
      path: '/$authorId'
      fullPath: '/author/$authorId'
      preLoaderRoute: typeof AuthorAuthorIdRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/author/analytics': {
      id: '/author/analytics'
      path: '/analytics'
      fullPath: '/author/analytics'
      preLoaderRoute: typeof AuthorAnalyticsRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/author/publish': {
      id: '/author/publish'
      path: '/publish'
      fullPath: '/author/publish'
      preLoaderRoute: typeof AuthorPublishRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$paperId': {
      id: '/research/$paperId'
      path: '/research/$paperId'
      fullPath: '/research/$paperId'
      preLoaderRoute: typeof ResearchPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/mine': {
      id: '/research/mine'
      path: '/research/mine'
      fullPath: '/research/mine'
      preLoaderRoute: typeof ResearchMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/submit': {
      id: '/research/submit'
      path: '/research/submit'
      fullPath: '/research/submit'
      preLoaderRoute: typeof ResearchSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/books/$bookId': {
      id: '/admin/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/admin/books/$bookId'
      preLoaderRoute: typeof AdminBooksBookIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/books/new': {
      id: '/admin/books/new'
      path: '/books/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AdminBooksNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/research/': {
      id: '/admin/research/'
      path: '/research'
      fullPath: '/admin/research/'
      preLoaderRoute: typeof AdminResearchIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/research/$paperId': {
      id: '/admin/research/$paperId'
      path: '/research/$paperId'
      fullPath: '/admin/research/$paperId'
      preLoaderRoute: typeof AdminResearchPaperIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support/$ticketId': {
      id: '/admin/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AdminSupportTicketIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/author/book/$bookId': {
      id: '/author/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/author/book/$bookId'
      preLoaderRoute: typeof AuthorBookBookIdRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTranslationRequestsRoute: typeof AdminTranslationRequestsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBooksBookIdRoute: typeof AdminBooksBookIdRoute
  AdminBooksNewRoute: typeof AdminBooksNewRoute
  AdminResearchPaperIdRoute: typeof AdminResearchPaperIdRoute
  AdminSupportTicketIdRoute: typeof AdminSupportTicketIdRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminResearchIndexRoute: typeof AdminResearchIndexRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTranslationRequestsRoute: AdminTranslationRequestsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBooksBookIdRoute: AdminBooksBookIdRoute,
  AdminBooksNewRoute: AdminBooksNewRoute,
  AdminResearchPaperIdRoute: AdminResearchPaperIdRoute,
  AdminSupportTicketIdRoute: AdminSupportTicketIdRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminResearchIndexRoute: AdminResearchIndexRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthorRouteRouteChildren {
  AuthorAuthorIdRoute: typeof AuthorAuthorIdRoute
  AuthorAnalyticsRoute: typeof AuthorAnalyticsRoute
  AuthorPublishRoute: typeof AuthorPublishRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  AuthorBookBookIdRoute: typeof AuthorBookBookIdRoute
}

const AuthorRouteRouteChildren: AuthorRouteRouteChildren = {
  AuthorAuthorIdRoute: AuthorAuthorIdRoute,
  AuthorAnalyticsRoute: AuthorAnalyticsRoute,
  AuthorPublishRoute: AuthorPublishRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  AuthorBookBookIdRoute: AuthorBookBookIdRoute,
}

const AuthorRouteRouteWithChildren = AuthorRouteRoute._addFileChildren(
  AuthorRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthorRouteRoute: AuthorRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LegalRoute: LegalRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SubscribeRoute: SubscribeRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
  ResearchPaperIdRoute: ResearchPaperIdRoute,
  ResearchMineRoute: ResearchMineRoute,
  ResearchSubmitRoute: ResearchSubmitRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
