/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthorRouteRouteImport } from './routes/author/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as AuthorAuthorIdRouteImport } from './routes/author/$authorId'
import { Route as AuthorAnalyticsRouteImport } from './routes/author.analytics'
import { Route as AuthorPublishRouteImport } from './routes/author.publish'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'
import { Route as AuthorBookBookIdRouteImport } from './routes/author.book.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRouteRoute = AuthorRouteRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthorAuthorIdRoute = AuthorAuthorIdRouteImport.update({
  id: '/$authorId',
  path: '/$authorId',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthorAnalyticsRoute = AuthorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const AuthorPublishRoute = AuthorPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthorRouteRoute,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorBookBookIdRoute = AuthorBookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => AuthorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/author': typeof AuthorRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/author/analytics': typeof AuthorAnalyticsRoute
  '/author/publish': typeof AuthorPublishRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/author/': typeof AuthorIndexRoute
  '/author/book/$bookId': typeof AuthorBookBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/author/analytics': typeof AuthorAnalyticsRoute
  '/author/publish': typeof AuthorPublishRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/author': typeof AuthorIndexRoute
  '/author/book/$bookId': typeof AuthorBookBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/author': typeof AuthorRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/author/analytics': typeof AuthorAnalyticsRoute
  '/author/publish': typeof AuthorPublishRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/author/': typeof AuthorIndexRoute
  '/author/book/$bookId': typeof AuthorBookBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/author'
    | '/auth'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/profile'
    | '/subscribe'
    | '/author/$authorId'
    | '/author/analytics'
    | '/author/publish'
    | '/book/$bookId'
    | '/read/$bookId'
    | '/author/'
    | '/author/book/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/profile'
    | '/subscribe'
    | '/author/$authorId'
    | '/author/analytics'
    | '/author/publish'
    | '/book/$bookId'
    | '/read/$bookId'
    | '/author'
    | '/author/book/$bookId'
  id:
    | '__root__'
    | '/'
    | '/author'
    | '/auth'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/profile'
    | '/subscribe'
    | '/author/$authorId'
    | '/author/analytics'
    | '/author/publish'
    | '/book/$bookId'
    | '/read/$bookId'
    | '/author/'
    | '/author/book/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorRouteRoute: typeof AuthorRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LegalRoute: typeof LegalRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SubscribeRoute: typeof SubscribeRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/author/$authorId': {
      id: '/author/$authorId'
      path: '/$authorId'
      fullPath: '/author/$authorId'
      preLoaderRoute: typeof AuthorAuthorIdRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/author/analytics': {
      id: '/author/analytics'
      path: '/analytics'
      fullPath: '/author/analytics'
      preLoaderRoute: typeof AuthorAnalyticsRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/author/publish': {
      id: '/author/publish'
      path: '/publish'
      fullPath: '/author/publish'
      preLoaderRoute: typeof AuthorPublishRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/book/$bookId': {
      id: '/author/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/author/book/$bookId'
      preLoaderRoute: typeof AuthorBookBookIdRouteImport
      parentRoute: typeof AuthorRouteRoute
    }
  }
}

interface AuthorRouteRouteChildren {
  AuthorAuthorIdRoute: typeof AuthorAuthorIdRoute
  AuthorAnalyticsRoute: typeof AuthorAnalyticsRoute
  AuthorPublishRoute: typeof AuthorPublishRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  AuthorBookBookIdRoute: typeof AuthorBookBookIdRoute
}

const AuthorRouteRouteChildren: AuthorRouteRouteChildren = {
  AuthorAuthorIdRoute: AuthorAuthorIdRoute,
  AuthorAnalyticsRoute: AuthorAnalyticsRoute,
  AuthorPublishRoute: AuthorPublishRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  AuthorBookBookIdRoute: AuthorBookBookIdRoute,
}

const AuthorRouteRouteWithChildren = AuthorRouteRoute._addFileChildren(
  AuthorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorRouteRoute: AuthorRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LegalRoute: LegalRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SubscribeRoute: SubscribeRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
